baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Fulan'
theme = 'hugo-bearblog'

enableRobotsTXT = true

[params]
  description = 'fulan'
  # Website icon (favicon). Use a square image, at least 32Ã—32 px (PNG or ICO).
  # Put your file in the static/ folder, then set the path from site root.
  favicon = "images/favicon.png"
